// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using Data.io.Lib;
using WebSocketSharp;

namespace Data.io
{
	public static class Client
	{
		//Create a socket with the specified uri
		public static Socket Create(string uri) {
			if (!uri.Contains ("ws://") && !uri.Contains ("wss://")) {
				if(uri.Contains("http://")) {
					uri = uri.Replace("http://", "ws://");
				}
				else if(uri.Contains("https://")) {
					uri = uri.Replace("https://", "wss://");
				}
				else {
					int index = uri.IndexOf(':');

					if(index > -1) {
						uri = "ws" + uri.Substring(index);
					}
					else {
						uri = "ws://" + uri;
					}
				}
			}

			return new Socket(new WebSocket(uri));
		}

		//Create a socket with additional protocol options for the websocket
		//See the documentation of websocket-sharp for the protocol options
		public static Socket Create(string uri, string[] protocols) {
			if (!uri.Contains ("ws://") && !uri.Contains ("wss://")) {
				if(uri.Contains("http://")) {
					uri = uri.Replace("http://", "ws://");
				}
				else if(uri.Contains("https://")) {
					uri = uri.Replace("https://", "wss://");
				}
				else {
					int index = uri.IndexOf(':');
					
					if(index > -1) {
						uri = "ws" + uri.Substring(index);
					}
					else {
						uri = "ws://" + uri;
					}
				}
			}

			return new Socket(new WebSocket(uri, protocols));
		}
	}
}

