// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;

namespace Data.io.Lib
{
	//Listener class for the EventEmitter
	//EventEmitter uses this internally
	public class Listener
	{
		public int type;
		public Delegate fn;

		public Listener (int type, Delegate fn)
		{
			this.type = type;
			this.fn = fn;
		}
	}
}

